// Component catalog: a descriptor per VizEngine component with editable
// property fields and a build(props) → source function. Powers the drag-drop
// composer (demo/composer.html) and any custom editor. Exposed as
// VizEngine.catalog.
//
// field.type ∈ 'text' | 'textarea' | 'lines' | 'select'

const fence = (kind, dirField) => (p) =>
  '```' + kind + (dirField && p.dir ? ' ' + p.dir : '') + (p.flags ? ' ' + p.flags : '') + '\n' + (p.body || '') + '\n```';
const directive = (name) => (p) =>
  ':::' + name + (p.args ? ' ' + p.args : '') + '\n' + (p.body || '') + '\n:::';
const bodyField = (label, type = 'textarea') => ({ key: 'body', label, type });

// helper to declare a component compactly
const C = (id, name, category, fields, build, def) => ({ id, name, category, fields, build, default: def });

export const CATALOG = [
  // ---------- Diagrams ----------
  C('graph', 'Flowchart (graph)', 'Diagrams',
    [{ key: 'dir', label: 'Direction', type: 'select', options: ['TD', 'LR', 'BT', 'RL'] },
     { key: 'flags', label: 'Flags', type: 'text' },
     bodyField('Nodes & edges')],
    fence('graph', true),
    { dir: 'TD', flags: '', body: 'a: [ @gear loader ]\nb: [ @skull payload ]\nc: ( @globe c2 )\na -> b : "unpack"\nb -> c : "beacon" [err]' }),
  C('tree', 'Tree', 'Diagrams', [bodyField('Indented nodes')], fence('tree'),
    { body: 'services.exe\n  svchost.exe\n  explorer.exe\n    malware.exe [diamond]' }),
  C('sequence', 'Sequence', 'Diagrams', [bodyField('Actors & messages')], fence('sequence'),
    { body: 'c: [ @user implant ]\ns: [ @server c2 ]\nc -> s : "beacon"\ns -> c : "task"' }),
  C('timeline', 'Timeline', 'Diagrams', [bodyField('stamp text per line')], fence('timeline'),
    { body: '00:00 detonation\n00:04 drops payload\n00:41 dns query' }),
  C('bars', 'Bars', 'Diagrams', [bodyField('label: value')], fence('bars'),
    { body: 'behavior: 92\nnetwork: 71\nstealth: 45' }),
  C('pie', 'Pie / donut', 'Diagrams', [bodyField('label: value')], fence('pie'),
    { body: 'trojan: 46\nstealer: 27\nclean: 12' }),
  C('gantt', 'Gantt', 'Diagrams', [bodyField('label: start dur')], fence('gantt'),
    { body: 'unpack: 0 2\nbeacon: 5 9\nexfil: 9 3' }),
  C('sankey', 'Sankey', 'Diagrams', [bodyField('src -> dst : weight')], fence('sankey'),
    { body: 'phish -> macro : 40\nmacro -> loader : 30\nloader -> exfil : 25' }),
  C('treemap', 'Treemap', 'Diagrams', [bodyField('name: value')], fence('treemap'),
    { body: 'dropper.exe\n  .text: 90\n  .rsrc: 120\n    icon: 30\n    strings: 90' }),
  C('flame', 'Flame graph', 'Diagrams', [bodyField('frame: value')], fence('flame'),
    { body: 'main: 100\n  unpack: 45\n  execute: 55\n    inject: 35' }),
  C('geomap', 'Geomap', 'Diagrams', [bodyField('id @ City | @icon label')], fence('geomap'),
    { body: 'victim @ New York | @user victim\nc2 @ Moscow | @skull C2\nvictim -> c2 | beacon [err] dashed' }),
  C('network', 'Network', 'Diagrams', [bodyField('nodes & edges')], fence('network'),
    { body: 'gw: [ @server gateway ]\nh1: [ host-1 ]\nh2: [ host-2 ]\ngw -> h1\ngw -> h2\nh1 -> h2' }),
  C('graph3d', 'Graph 3D', 'Diagrams', [bodyField('nodes & edges')], fence('graph3d'),
    { body: 'root: [ services.exe ]\na: [ svchost.exe ]\nb: [ malware.exe ]\nroot -> a\na -> b' }),
  C('bars3d', 'Bars 3D', 'Diagrams', [bodyField('label: value')], fence('bars3d'),
    { body: 'behavior: 92\nnetwork: 71\nstealth: 45' }),
  C('mermaid', 'Mermaid import', 'Diagrams', [bodyField('Mermaid flowchart')], fence('mermaid'),
    { body: 'flowchart TD\n  A[explorer.exe] --> B{Suspicious?}\n  B -->|yes| C(malware.exe)' }),
  C('dot', 'Graphviz DOT import', 'Diagrams', [bodyField('DOT digraph')], fence('dot'),
    { body: 'digraph { rankdir=LR; a -> b [label="open"]; b -> c; }' }),

  // ---------- Data / metrics ----------
  C('stat', 'Stat tiles', 'Data', [{ key: 'body', label: 'value | label | delta', type: 'lines' }], directive('stat'),
    { body: '92 / 100 | Behavior | +14\n3 | Processes |\n1 | C2 | -2' }),
  C('score', 'Score', 'Data',
    [{ key: 'value', label: 'Value', type: 'text' }, { key: 'grade', label: 'Grade', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `:::score\n${p.value || ''} ${p.grade || ''} ${p.label || ''}\n:::`,
    { value: '92', grade: 'A', label: 'threat' }),
  C('gauge', 'Gauge', 'Data',
    [{ key: 'value', label: 'Value', type: 'text' }, { key: 'max', label: 'Max', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `:::gauge\n${p.value || 0}${p.max ? ' / ' + p.max : ''} ${p.label || ''}\n:::`,
    { value: '78', max: '', label: 'detection' }),
  C('ring', 'Progress ring', 'Data',
    [{ key: 'value', label: 'Value', type: 'text' }, { key: 'max', label: 'Max', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `:::ring\n${p.value || 0}${p.max ? ' / ' + p.max : ''} ${p.label || ''}\n:::`,
    { value: '72', max: '', label: 'coverage' }),
  C('rating', 'Rating', 'Data',
    [{ key: 'n', label: 'Filled', type: 'text' }, { key: 'm', label: 'Total', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `:::rating\n${p.n || 0} / ${p.m || 5} ${p.label || ''}\n:::`,
    { n: '4', m: '5', label: 'confidence' }),
  C('status', 'Status list', 'Data', [{ key: 'body', label: 'state label (ok/warn/err/info)', type: 'lines' }], directive('status'),
    { body: 'ok gateway reachable\nwarn high dns volume\nerr c2 handshake' }),
  C('heatmap', 'Heatmap', 'Data', [{ key: 'body', label: 'rows of numbers', type: 'lines' }], directive('heatmap'),
    { body: '1 3 5 8 4\n2 9 4 1 6\n7 2 6 3 5' }),
  C('legend', 'Legend', 'Data', [{ key: 'body', label: 'color label', type: 'lines' }], directive('legend'),
    { body: 'err critical\nwarn suspicious\nok benign' }),
  C('chips', 'Chips', 'Data', [{ key: 'body', label: 'comma list (!crit +ok ~warn)', type: 'text' }], (p) => `:::chips\n${p.body || ''}\n:::`,
    { body: '!critical, +verified, ~evasion, stealer' }),
  C('dtimeline', 'Doc timeline', 'Data', [{ key: 'body', label: 'stamp | text', type: 'lines' }], directive('dtimeline'),
    { body: '00:00 | detonation\n00:03 | unpacks payload\n00:41 | dns query' }),
  C('swatches', 'Swatches', 'Data', [{ key: 'body', label: '#hex name, ...', type: 'text' }], (p) => `:::swatches\n${p.body || ''}\n:::`,
    { body: '#ff2e63 danger, #36f9f6 accent, #39ff14 ok, #ffd400 warn' }),
  C('meta', 'Meta panel', 'Data', [{ key: 'body', label: 'term :: value', type: 'lines' }], directive('meta'),
    { body: 'SHA-256 :: 9f86d0…\nC2 :: 45.13.7.2:443\nFamily :: RedLine' }),
  C('sparkinline', 'Sparkline (inline)', 'Data', [{ key: 'vals', label: 'values', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `${p.label || 'trend'} [[spark ${p.vals || '1,2,3'}]]`, { vals: '3,7,4,9,6,11,8', label: 'DNS volume' }),

  // ---------- Malware ----------
  C('ioc', 'IOC rows', 'Malware', [{ key: 'body', label: 'type value | note', type: 'lines' }], directive('ioc'),
    { body: 'sha256  9f86d081884c7d659a2feaa0c55ad015 | dropper\nip  45.13.7.2:443 | c2\ndomain  evil-c2.example' }),
  C('verdict', 'Verdict banner', 'Malware',
    [{ key: 'level', label: 'Level', type: 'select', options: ['malicious', 'suspicious', 'clean', 'unknown'] }, { key: 'text', label: 'Text', type: 'text' }],
    (p) => `:::verdict\n${p.level || 'malicious'} ${p.text || ''}\n:::`,
    { level: 'malicious', text: 'score 92/100 · family RedLine' }),
  C('mitre', 'MITRE chips', 'Malware', [{ key: 'body', label: 'Txxxx Name, ...', type: 'text' }], (p) => `:::mitre\n${p.body || ''}\n:::`,
    { body: 'T1055 Process Injection, T1071 C2, T1547.001 Registry Run Keys' }),
  C('hexdump', 'Hexdump', 'Malware', [bodyField('text to dump')], directive('hexdump'),
    { body: 'MZ..dropper.exe payload begins here with bytes' }),
  C('yara', 'YARA rule', 'Malware', [bodyField('yara rule')], directive('yara'),
    { body: 'rule RedLine {\n  strings:\n    $a = "evil-c2.example"\n  condition:\n    any of them\n}' }),
  C('compare', 'Compare', 'Malware', [{ key: 'a', label: 'Before', type: 'textarea' }, { key: 'b', label: 'After', type: 'textarea' }],
    (p) => `:::compare\n== Before\n${p.a || ''}\n== After\n${p.b || ''}\n:::`,
    { a: 'plain http.get(host)', b: 'https.post(host, encrypt())' }),

  // ---------- Presentation ----------
  C('callout', 'Callout', 'Presentation',
    [{ key: 'kind', label: 'Kind', type: 'select', options: ['note', 'tip', 'warn', 'danger', 'success'] }, { key: 'title', label: 'Title', type: 'text' }, { key: 'body', label: 'Body', type: 'textarea' }],
    (p) => `> [!${p.kind || 'note'}] ${p.title || ''}\n` + (p.body || '').split('\n').map((l) => '> ' + l).join('\n'),
    { kind: 'danger', title: 'Verdict: malicious', body: 'Behavior score **92/100**.' }),
  C('alert', 'Alert banner', 'Presentation',
    [{ key: 'kind', label: 'Kind', type: 'select', options: ['note', 'tip', 'warn', 'danger', 'success'] }, { key: 'msg', label: 'Message', type: 'text' }],
    (p) => `:::alert ${p.kind || 'danger'} ${p.msg || ''}\n:::`,
    { kind: 'danger', msg: 'Beacon to 45.13.7.2 detected on host-7' }),
  C('banner', 'Hero banner', 'Presentation', [{ key: 'title', label: 'Title', type: 'text' }, { key: 'sub', label: 'Subtitle', type: 'text' }],
    (p) => `:::banner ${p.title || ''}${p.sub ? ' | ' + p.sub : ''}\n:::`,
    { title: 'Threat Report — sample.exe', sub: 'Windows 10 sandbox · 120s' }),
  C('note', 'Sticky note', 'Presentation', [{ key: 'pin', label: 'Pin', type: 'text' }, { key: 'body', label: 'Body', type: 'textarea' }],
    (p) => `:::note ${p.pin || ''}\n${p.body || ''}\n:::`,
    { pin: 'analyst note', body: 'Sleeps ~40s before beaconing.' }),
  C('quote', 'Pull quote', 'Presentation', [{ key: 'text', label: 'Quote', type: 'textarea' }, { key: 'author', label: 'Author', type: 'text' }],
    (p) => `:::quote\n${p.text || ''}${p.author ? ' — ' + p.author : ''}\n:::`,
    { text: 'A textbook stealer.', author: 'Threat Intel Team' }),

  // ---------- Layout ----------
  C('tabs', 'Tabs', 'Layout', [bodyField('== Label sections')], directive('tabs'),
    { body: '== Summary\nSample is a **stealer**.\n== IOCs\n- 45.13.7.2:443' }),
  C('accordion', 'Accordion', 'Layout', [bodyField('== Label sections')], directive('accordion'),
    { body: '== Static\nNo packer.\n== Dynamic\nBeacons every 45s.' }),
  C('steps', 'Steps', 'Layout', [{ key: 'body', label: 'x done / > current / todo', type: 'lines' }], directive('steps'),
    { body: 'x unpack\nx extract IOCs\n> write yara\npublish' }),
  C('columns', 'Columns', 'Layout', [bodyField('== Label sections')], directive('columns'),
    { body: '== Host\nedr-agent · win10\n== Network\ngateway 10.0.0.1' }),
  C('grid', 'Card grid', 'Layout', [bodyField('== Label sections')], directive('grid'),
    { body: '== CPU\n[[progress 34]]\n== Memory\n[[progress 71]]' }),
  C('card', 'Card', 'Layout', [{ key: 'args', label: 'Title', type: 'text' }, bodyField('Body')], directive('card'),
    { args: 'Sample metadata', body: 'File: dropper.exe · 214 KB\nSigned: no' }),
  C('divider', 'Divider', 'Layout', [{ key: 'label', label: 'Label', type: 'text' }], (p) => `:::divider ${p.label || ''} :::`,
    { label: 'evidence' }),

  // ---------- Widgets ----------
  C('terminal', 'Terminal', 'Widgets', [{ key: 'args', label: 'Title', type: 'text' }, bodyField('lines ($ = prompt)')], directive('terminal'),
    { args: 'detonation', body: '$ ./sample.exe\ndropping payload to %TEMP%\nThe operation completed.' }),
  C('kbd', 'Keyboard keys', 'Widgets', [{ key: 'keys', label: 'Keys', type: 'text' }], (p) => `:::kbd ${p.keys || ''} :::`, { keys: 'Ctrl + Shift + P' }),
  C('spinner', 'Spinner', 'Widgets', [{ key: 'label', label: 'Label', type: 'text' }], (p) => `:::spinner ${p.label || ''}\n:::`, { label: 'scanning…' }),
  C('loader', 'Loader bar', 'Widgets', [{ key: 'label', label: 'Label', type: 'text' }], (p) => `:::loader ${p.label || ''}\n:::`, { label: 'detonating sample' }),
  C('pulsedot', 'Pulse dot', 'Widgets', [{ key: 'label', label: 'Label', type: 'text' }], (p) => `:::pulsedot ${p.label || ''}\n:::`, { label: 'host-7 · live' }),
  C('typewriter', 'Typewriter', 'Widgets', [{ key: 'text', label: 'Text', type: 'text' }], (p) => `:::typewriter ${p.text || ''}\n:::`, { text: 'analyzing 45.13.7.2 → RedLine' }),
  C('beacon', 'Beacon rings', 'Widgets', [{ key: 'label', label: 'Label', type: 'text' }], (p) => `:::beacon ${p.label || ''}\n:::`, { label: 'C2 ping every 45s' }),
  C('radar', 'Radar', 'Widgets', [], () => ':::radar\n:::', {}),
  C('countdown', 'Countdown', 'Widgets', [{ key: 'dur', label: 'Duration', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }],
    (p) => `:::countdown ${p.dur || '7s'}\n${p.label || ''}\n:::`, { dur: '7s', label: 'sandbox TTL' }),
  C('matrix', 'Matrix rain', 'Widgets', [], () => ':::matrix\n:::', {}),

  // ---------- Document ----------
  C('prose', 'Prose / markdown', 'Document', [bodyField('Markdown + [[widgets]]')],
    (p) => p.body || '', { body: '## Section\nText with **bold**, `code`, [[!badge]], [[progress 72]], [[sev 4/5]].' }),
  C('table', 'Table', 'Document', [bodyField('GFM pipe table')], (p) => p.body || '',
    { body: '| Indicator | Value | Conf |\n|:--|:--|--:|\n| SHA-256 | `9f86…` | high |\n| C2 | `45.13.7.2` | high |' }),
  C('code', 'Code block', 'Document', [{ key: 'lang', label: 'Language', type: 'text' }, bodyField('Code')],
    (p) => '```' + (p.lang || '') + '\n' + (p.body || '') + '\n```', { lang: 'python', body: 'def beacon(host):\n    return https.post(host)' }),
  C('tasklist', 'Task list', 'Document', [bodyField('- [x] / - [ ] items')], (p) => p.body || '',
    { body: '- [x] unpacked\n- [x] extracted IOCs\n- [ ] write yara' }),
  C('filetree', 'File tree', 'Document', [bodyField('indented tree')], fence('filetree'),
    { body: '%TEMP%/\n  dropper.exe\n  cfg/\n    settings.dat' }),
  C('diff', 'Diff', 'Document', [bodyField('+/- lines')], fence('diff'),
    { body: '  function beacon(host) {\n-   return http.get(host);\n+   return https.post(host);' }),
  C('deflist', 'Definition list', 'Document', [{ key: 'body', label: 'term :: value', type: 'lines' }], (p) => p.body || '',
    { body: 'SHA-256 :: 9f86d0…\nC2 :: 45.13.7.2:443' }),
  C('collapse', 'Collapsible', 'Document', [{ key: 'args', label: 'Summary', type: 'text' }, bodyField('Body')],
    (p) => `+++ ${p.args || 'Details'}\n${p.body || ''}\n+++`, { args: 'Raw strings', body: 'GetProcAddress\nVirtualAlloc' }),
  C('htmlpreview', 'HTML preview', 'Document', [bodyField('HTML')], (p) => '```html\n' + (p.body || '') + '\n```',
    { body: '<h3>Live preview</h3>\n<button onclick="this.textContent=\'ok\'">click</button>' }),
];

export const CATALOG_CATEGORIES = [...new Set(CATALOG.map((c) => c.category))];
export const catalogById = (id) => CATALOG.find((c) => c.id === id);
